on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Sphinx
      run: pip install sphinx
    - name: Build documentation using Sphinx
      run: |
        rm -r docs/
        mkdir docs
        cd docs
        sphinx-quickstart -p pyiohat -a 'Tristan Ranff, Manuel Kösters, Artyom Vlasov, Christian Fufezan' -v ${{ github.ref_name }} -l en --no-sep -q --ext-autodoc
        sphinx-apidoc -o source/ ../pyiohat
        make html
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - name: Checkout Github Pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit and push documentation changes
      run: |
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        git push
